# Concate,combining data frame

In [1]:
import pandas as pd

In [23]:
data1={'Roll No':[1,2,3],
      'Subject':['A','B','C']}
df1=pd.DataFrame(data1)

In [24]:
data1

{'Roll No': [1, 2, 3], 'Subject': ['A', 'B', 'C']}

In [25]:
df1

   Roll No Subject
0        1       A
1        2       B
2        3       C

In [26]:
data2={'Roll No':[4,5,6],
      'Subject':['D','E','F']}
df2=pd.DataFrame(data2)

In [27]:
df2

   Roll No Subject
0        4       D
1        5       E
2        6       F

In [28]:
#concatenate dataframe along with column and index remains as it is
result_df=pd.concat([df1,df2],axis=0,ignore_index=True)
print(result_df)

   Roll No Subject
0        1       A
1        2       B
2        3       C
3        4       D
4        5       E
5        6       F

# Merging

In [32]:
import pandas as pd
df3=pd.DataFrame({'ID':[1,2,3],'Name':['Alice','Bob','Charlie']})
df4=pd.DataFrame({'ID':[2,3,4],'Age':[25,30,35]})

In [34]:
df3.head()

   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie

In [35]:
df4.head()

   ID  Age
0   2   25
1   3   30
2   4   35

In [36]:
merge_inner=pd.merge(df3,df4,on='ID',how='inner')
print("\nStep2: Inner Join (default)")
print(merge_inner)

Step2: Inner Join (default)
   ID     Name  Age
0   2      Bob   25
1   3  Charlie   30

In [39]:
merge_left=pd.merge(df3,df4,on='ID',how='left')
print("\n Step 3:Left Join")
print(merge_left)

 Step 3:Left Join
   ID     Name   Age
0   1    Alice   NaN
1   2      Bob  25.0
2   3  Charlie  30.0

In [40]:
merge_right=pd.merge(df3,df4,on='ID',how='right')
print("\n Step 3:Right Join")
print(merge_right)

 Step 3:Right Join
   ID     Name  Age
0   2      Bob   25
1   3  Charlie   30
2   4      NaN   35

In [41]:
merge_outer=pd.merge(df3,df4,on='ID',how='outer')
print("\n Step 5: Outer Join")
print(merge_outer)

 Step 5: Outer Join
   ID     Name   Age
0   1    Alice   NaN
1   2      Bob  25.0
2   3  Charlie  30.0
3   4      NaN  35.0

# Join

In [45]:
import pandas as pd
df5=pd.DataFrame({'Roll No':[1,2,3],'Name':['x','y','z']},index=[1,2,3])
df6=pd.DataFrame({'Score':[4,5,6],'Grade':['a','b','c']},index=[2,3,4])

In [47]:
df5

   Roll No Name
1        1    x
2        2    y
3        3    z

In [48]:
df6

   Score Grade
2      4     a
3      5     b
4      6     c

In [49]:
resultjoin=df5.join(df6,how='inner')
print(resultjoin)

   Roll No Name  Score Grade
2        2    y      4     a
3        3    z      5     b

 ## Filter(creating subset dataframe by rows or columns)