# Concate,combining data frame

In [1]:
import pandas as pd

In [23]:
data1={'Roll No':[1,2,3],
      'Subject':['A','B','C']}
df1=pd.DataFrame(data1)

In [24]:
data1

{'Roll No': [1, 2, 3], 'Subject': ['A', 'B', 'C']}

In [25]:
df1

   Roll No Subject
0        1       A
1        2       B
2        3       C

In [26]:
data2={'Roll No':[4,5,6],
      'Subject':['D','E','F']}
df2=pd.DataFrame(data2)

In [27]:
df2

   Roll No Subject
0        4       D
1        5       E
2        6       F

In [28]:
#concatenate dataframe along with column and index remains as it is
result_df=pd.concat([df1,df2],axis=0,ignore_index=True)
print(result_df)

   Roll No Subject
0        1       A
1        2       B
2        3       C
3        4       D
4        5       E
5        6       F

# Merging

In [32]:
import pandas as pd
df3=pd.DataFrame({'ID':[1,2,3],'Name':['Alice','Bob','Charlie']})
df4=pd.DataFrame({'ID':[2,3,4],'Age':[25,30,35]})

In [34]:
df3.head()

   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie

In [35]:
df4.head()

   ID  Age
0   2   25
1   3   30
2   4   35

In [36]:
merge_inner=pd.merge(df3,df4,on='ID',how='inner')
print("\nStep2: Inner Join (default)")
print(merge_inner)

Step2: Inner Join (default)
   ID     Name  Age
0   2      Bob   25
1   3  Charlie   30

In [39]:
merge_left=pd.merge(df3,df4,on='ID',how='left')
print("\n Step 3:Left Join")
print(merge_left)

 Step 3:Left Join
   ID     Name   Age
0   1    Alice   NaN
1   2      Bob  25.0
2   3  Charlie  30.0

In [40]:
merge_right=pd.merge(df3,df4,on='ID',how='right')
print("\n Step 3:Right Join")
print(merge_right)

 Step 3:Right Join
   ID     Name  Age
0   2      Bob   25
1   3  Charlie   30
2   4      NaN   35

In [41]:
merge_outer=pd.merge(df3,df4,on='ID',how='outer')
print("\n Step 5: Outer Join")
print(merge_outer)

 Step 5: Outer Join
   ID     Name   Age
0   1    Alice   NaN
1   2      Bob  25.0
2   3  Charlie  30.0
3   4      NaN  35.0

# Join

In [45]:
import pandas as pd
df5=pd.DataFrame({'Roll No':[1,2,3],'Name':['x','y','z']},index=[1,2,3])
df6=pd.DataFrame({'Score':[4,5,6],'Grade':['a','b','c']},index=[2,3,4])

In [47]:
df5

   Roll No Name
1        1    x
2        2    y
3        3    z

In [48]:
df6

   Score Grade
2      4     a
3      5     b
4      6     c

In [49]:
resultjoin=df5.join(df6,how='inner')
print(resultjoin)

   Roll No Name  Score Grade
2        2    y      4     a
3        3    z      5     b

 ## Filter(creating subset dataframe by rows or columns)

In [1]:
import pandas as pd

In [2]:
df_sal1=pd.read_csv("salaries.csv")
df_sal1.head()

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [3]:
df_sal1.filter(items=['rank','salary'])

         rank  salary
0        Prof  186960
1        Prof   93000
2        Prof  110515
3        Prof  131205
4        Prof  104800
..        ...     ...
73       Prof  105450
74  AssocProf  104542
75       Prof  124312
76       Prof  109954
77       Prof  109646

[78 rows x 2 columns]

In [4]:
df_sal1[['rank','sex','salary']]

         rank     sex  salary
0        Prof    Male  186960
1        Prof    Male   93000
2        Prof    Male  110515
3        Prof    Male  131205
4        Prof    Male  104800
..        ...     ...     ...
73       Prof  Female  105450
74  AssocProf  Female  104542
75       Prof  Female  124312
76       Prof  Female  109954
77       Prof  Female  109646

[78 rows x 3 columns]

In [5]:
df_sal1[df_sal1['sex']=='Male']

         rank discipline  phd  service   sex  salary
0        Prof          B   56       49  Male  186960
1        Prof          A   12        6  Male   93000
2        Prof          A   23       20  Male  110515
3        Prof          A   40       31  Male  131205
4        Prof          B   20       18  Male  104800
5        Prof          A   20       20  Male  122400
6   AssocProf          A   20       17  Male   81285
7        Prof          A   18       18  Male  126300
8        Prof          A   29       19  Male   94350
9        Prof          A   51       51  Male   57800
10       Prof          B   39       33  Male  128250
11       Prof          B   23       23  Male  134778
12   AsstProf          B    1        0  Male   88000
13       Prof          B   35       33  Male  162200
14       Prof          B   25       19  Male  153750
15       Prof          B   17        3  Male  150480
16   AsstProf          B    8        3  Male   75044
17   AsstProf          B    4        0  Male   92000
18       Prof          A   19        7  Male  107300
19       Prof          A   29       27  Male  150500
20   AsstProf          B    4        4  Male   92000
21       Prof          A   33       30  Male  103106
22   AsstProf          A    4        2  Male   73000
23   AsstProf          A    2        0  Male   85000
24       Prof          A   30       23  Male   91100
25       Prof          B   35       31  Male   99418
26       Prof          A   38       19  Male  148750
27       Prof          A   45       43  Male  155865
28   AsstProf          B    7        2  Male   91300
29       Prof          B   21       20  Male  123683
30  AssocProf          B    9        7  Male  107008
31       Prof          B   22       21  Male  155750
32       Prof          A   27       19  Male  103275
33       Prof          B   18       18  Male  120000
34  AssocProf          B   12        8  Male  119800
35       Prof          B   28       23  Male  126933
36       Prof          B   45       45  Male  146856
37       Prof          A   20        8  Male  102000
38   AsstProf          B    4        3  Male   91000

In [6]:
df_sal1['sex']=='Male'

0      True
1      True
2      True
3      True
4      True
      ...
73    False
74    False
75    False
76    False
77    False
Name: sex, Length: 78, dtype: bool

In [7]:
df_sal1[df_sal1['salary']>120000]

    rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
3   Prof          A   40       31    Male  131205
5   Prof          A   20       20    Male  122400
7   Prof          A   18       18    Male  126300
10  Prof          B   39       33    Male  128250
11  Prof          B   23       23    Male  134778
13  Prof          B   35       33    Male  162200
14  Prof          B   25       19    Male  153750
15  Prof          B   17        3    Male  150480
19  Prof          A   29       27    Male  150500
26  Prof          A   38       19    Male  148750
27  Prof          A   45       43    Male  155865
29  Prof          B   21       20    Male  123683
31  Prof          B   22       21    Male  155750
35  Prof          B   28       23    Male  126933
36  Prof          B   45       45    Male  146856
39  Prof          B   18       18  Female  129000
40  Prof          A   39       36  Female  137000
44  Prof          B   23       19  Female  151768
45  Prof          B   25       25  Female  140096
49  Prof          B   17       18  Female  122960
51  Prof          B   20       14  Female  127512
58  Prof          B   36       26  Female  144651
72  Prof          B   24       15  Female  161101
75  Prof          B   17       17  Female  124312

In [8]:
df_sal1.head()

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [9]:
df_sal1[df_sal1[['rank','discipline','phd','service','salary']]=='Female']

   rank discipline  phd  service  sex  salary
0   NaN        NaN  NaN      NaN  NaN     NaN
1   NaN        NaN  NaN      NaN  NaN     NaN
2   NaN        NaN  NaN      NaN  NaN     NaN
3   NaN        NaN  NaN      NaN  NaN     NaN
4   NaN        NaN  NaN      NaN  NaN     NaN
..  ...        ...  ...      ...  ...     ...
73  NaN        NaN  NaN      NaN  NaN     NaN
74  NaN        NaN  NaN      NaN  NaN     NaN
75  NaN        NaN  NaN      NaN  NaN     NaN
76  NaN        NaN  NaN      NaN  NaN     NaN
77  NaN        NaN  NaN      NaN  NaN     NaN

[78 rows x 6 columns]

In [10]:
df_sal1[(df_sal1['salary']>120000)& (df_sal1['discipline']=='B')]

    rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
10  Prof          B   39       33    Male  128250
11  Prof          B   23       23    Male  134778
13  Prof          B   35       33    Male  162200
14  Prof          B   25       19    Male  153750
15  Prof          B   17        3    Male  150480
29  Prof          B   21       20    Male  123683
31  Prof          B   22       21    Male  155750
35  Prof          B   28       23    Male  126933
36  Prof          B   45       45    Male  146856
39  Prof          B   18       18  Female  129000
44  Prof          B   23       19  Female  151768
45  Prof          B   25       25  Female  140096
49  Prof          B   17       18  Female  122960
51  Prof          B   20       14  Female  127512
58  Prof          B   36       26  Female  144651
72  Prof          B   24       15  Female  161101
75  Prof          B   17       17  Female  124312

In [11]:
df_sal1[(df_sal1['rank']=='Prof')& (df_sal1['sex']=='Female')]

    rank discipline  phd  service     sex  salary
39  Prof          B   18       18  Female  129000
40  Prof          A   39       36  Female  137000
44  Prof          B   23       19  Female  151768
45  Prof          B   25       25  Female  140096
48  Prof          B   17       17  Female  111512
49  Prof          B   17       18  Female  122960
51  Prof          B   20       14  Female  127512
52  Prof          A   12        0  Female  105000
58  Prof          B   36       26  Female  144651
63  Prof          A   29       27  Female   91000
65  Prof          A   36       19  Female  117555
67  Prof          A   17       11  Female   90450
69  Prof          A   28        7  Female  116450
72  Prof          B   24       15  Female  161101
73  Prof          B   18       10  Female  105450
75  Prof          B   17       17  Female  124312
76  Prof          A   28       14  Female  109954
77  Prof          A   23       15  Female  109646

## Creating a bonus column from salary column

In [12]:
df_sal1['bonus']=df_sal1['salary']*.10

In [13]:
df_sal1

         rank discipline  phd  service     sex  salary    bonus
0        Prof          B   56       49    Male  186960  18696.0
1        Prof          A   12        6    Male   93000   9300.0
2        Prof          A   23       20    Male  110515  11051.5
3        Prof          A   40       31    Male  131205  13120.5
4        Prof          B   20       18    Male  104800  10480.0
..        ...        ...  ...      ...     ...     ...      ...
73       Prof          B   18       10  Female  105450  10545.0
74  AssocProf          B   19        6  Female  104542  10454.2
75       Prof          B   17       17  Female  124312  12431.2
76       Prof          A   28       14  Female  109954  10995.4
77       Prof          A   23       15  Female  109646  10964.6

[78 rows x 7 columns]

## creating a new phd columns where phd add by 10

In [15]:
df_sal1['new_phd']=df_sal1['phd']+10

In [16]:
df_sal1

         rank discipline  phd  service     sex  salary    bonus  new_phd
0        Prof          B   56       49    Male  186960  18696.0       66
1        Prof          A   12        6    Male   93000   9300.0       22
2        Prof          A   23       20    Male  110515  11051.5       33
3        Prof          A   40       31    Male  131205  13120.5       50
4        Prof          B   20       18    Male  104800  10480.0       30
..        ...        ...  ...      ...     ...     ...      ...      ...
73       Prof          B   18       10  Female  105450  10545.0       28
74  AssocProf          B   19        6  Female  104542  10454.2       29
75       Prof          B   17       17  Female  124312  12431.2       27
76       Prof          A   28       14  Female  109954  10995.4       38
77       Prof          A   23       15  Female  109646  10964.6       33

[78 rows x 8 columns]

In [18]:
df_sal1['Total']=df_sal1['salary']+df_sal1['bonus']

In [19]:
df_sal1

,rank,discipline,phd,service,sex,salary,bonus,new_phd,Total
0,Prof,B,56,49,Male,186960,18696.0,66,205656.0
1,Prof,A,12,6,Male,93000,9300.0,22,102300.0
2,Prof,A,23,20,Male,110515,11051.5,33,121566.5
3,Prof,A,40,31,Male,131205,13120.5,50,144325.5
4,Prof,B,20,18,Male,104800,10480.0,30,115280.0
...,...,...,...,...,...,...,...,...,...
73,Prof,B,18,10,Female,105450,10545.0,28,115995.0
74,AssocProf,B,19,6,Female,104542,10454.2,29,114996.2
75,Prof,B,17,17,Female,124312,12431.2,27,136743.2
76,Prof,A,28,14,Female,109954,10995.4,38,120949.4
77,Prof,A,23,15,Female,109646,10964.6,33,120610.6

### Saving to a file

In [20]:
df_sal1.to_csv('newsalary.csv')