In [1]:
import pandas as pd
data=pd.read_csv('cars.csv')

In [2]:
data.head(10)

,YEAR,Make,Model,Size,(kW),Unnamed: 5,TYPE,CITY (kWh/100 km),HWY (kWh/100 km),COMB (kWh/100 km),CITY (Le/100 km),HWY (Le/100 km),COMB (Le/100 km),(g/km),RATING,(km),TIME (h)
0,2012,MITSUBISHI,i-MiEV,SUBCOMPACT,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,NaN,100,7
1,2012,NISSAN,LEAF,MID-SIZE,80,A1,B,19.3,23.0,21.1,2.2,2.6,2.4,0,NaN,117,7
2,2013,FORD,FOCUS ELECTRIC,COMPACT,107,A1,B,19.0,21.1,20.0,2.1,2.4,2.2,0,NaN,122,4
3,2013,MITSUBISHI,i-MiEV,SUBCOMPACT,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,NaN,100,7
4,2013,NISSAN,LEAF,MID-SIZE,80,A1,B,19.3,23.0,21.1,2.2,2.6,2.4,0,NaN,117,7
5,2013,SMART,FORTWO ELECTRIC DRIVE CABRIOLET,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
6,2013,SMART,FORTWO ELECTRIC DRIVE COUPE,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
7,2013,TESLA,MODEL S (40 kWh battery),FULL-SIZE,270,A1,B,22.4,21.9,22.2,2.5,2.5,2.5,0,NaN,224,6
8,2013,TESLA,MODEL S (60 kWh battery),FULL-SIZE,270,A1,B,22.2,21.7,21.9,2.5,2.4,2.5,0,NaN,335,10
9,2013,TESLA,MODEL S (85 kWh battery),FULL-SIZE,270,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   YEAR               53 non-null     int64
 1   Make               53 non-null     object
 2   Model              53 non-null     object
 3   Size               53 non-null     object
 4   (kW)               53 non-null     int64
 5   Unnamed: 5         53 non-null     object
 6   TYPE               53 non-null     object
 7   CITY (kWh/100 km)  53 non-null     float64
 8   HWY (kWh/100 km)   53 non-null     float64
 9   COMB (kWh/100 km)  53 non-null     float64
 10  CITY (Le/100 km)   53 non-null     float64
 11  HWY (Le/100 km)    53 non-null     float64
 12  COMB (Le/100 km)   53 non-null     float64
 13  (g/km)             53 non-null     int64
 14  RATING             19 non-null     float64
 15  (km)               53 non-null     int64
 16  TIME (h)           53 non-null     int64
dtypes: float64(7), int64(5), object(5)
memory usage: 7.2+ KB

In [5]:
data.columns

Index(['YEAR', 'Make', 'Model', 'Size', '(kW)', 'Unnamed: 5', 'TYPE',
       'CITY (kWh/100 km)', 'HWY (kWh/100 km)', 'COMB (kWh/100 km)',
       'CITY (Le/100 km)', 'HWY (Le/100 km)', 'COMB (Le/100 km)', '(g/km)',
       'RATING', '(km)', 'TIME (h)'],
      dtype='object')

In [8]:
data.columns.tolist()

['YEAR',
 'Make',
 'Model',
 'Size',
 '(kW)',
 'Unnamed: 5',
 'TYPE',
 'CITY (kWh/100 km)',
 'HWY (kWh/100 km)',
 'COMB (kWh/100 km)',
 'CITY (Le/100 km)',
 'HWY (Le/100 km)',
 'COMB (Le/100 km)',
 '(g/km)',
 'RATING',
 '(km)',
 'TIME (h)']

In [9]:
data.dtypes

YEAR                   int64
Make                  object
Model                 object
Size                  object
(kW)                   int64
Unnamed: 5            object
TYPE                  object
CITY (kWh/100 km)    float64
HWY (kWh/100 km)     float64
COMB (kWh/100 km)    float64
CITY (Le/100 km)     float64
HWY (Le/100 km)      float64
COMB (Le/100 km)     float64
(g/km)                 int64
RATING               float64
(km)                   int64
TIME (h)               int64
dtype: object

In [11]:
data.describe()#summary of numeric columns

,YEAR,(kW),CITY (kWh/100 km),HWY (kWh/100 km),COMB (kWh/100 km),CITY (Le/100 km),HWY (Le/100 km),COMB (Le/100 km),(g/km),RATING,(km),TIME (h)
count,53.000000,53.000000,53.00000,53.000000,53.000000,53.000000,53.000000,53.000000,53.0,19.0,53.000000,53.000000
mean,2014.735849,190.622642,19.64717,21.633962,20.541509,2.207547,2.422642,2.301887,0.0,10.0,239.169811,8.471698
std,1.227113,155.526429,3.00100,1.245753,1.979455,0.344656,0.143636,0.212576,0.0,0.0,141.426352,2.991036
min,2012.000000,35.000000,15.20000,18.800000,16.800000,1.700000,2.100000,1.900000,0.0,10.0,100.000000,4.000000
25%,2014.000000,80.000000,17.00000,20.800000,18.700000,1.900000,2.300000,2.100000,0.0,10.0,117.000000,7.000000
50%,2015.000000,107.000000,19.00000,21.700000,20.000000,2.100000,2.400000,2.200000,0.0,10.0,135.000000,8.000000
75%,2016.000000,283.000000,22.40000,22.500000,22.100000,2.500000,2.500000,2.500000,0.0,10.0,402.000000,12.000000
max,2016.000000,568.000000,23.90000,23.300000,23.600000,2.700000,2.600000,2.600000,0.0,10.0,473.000000,12.000000

In [13]:
#standard deviation
numeric_data=data.select_dtypes(include='number')

In [16]:
std_dev=data.std(numeric_only=True)

In [17]:
print(std_dev)

YEAR                   1.227113
(kW)                 155.526429
CITY (kWh/100 km)      3.001000
HWY (kWh/100 km)       1.245753
COMB (kWh/100 km)      1.979455
CITY (Le/100 km)       0.344656
HWY (Le/100 km)        0.143636
COMB (Le/100 km)       0.212576
(g/km)                 0.000000
RATING                 0.000000
(km)                 141.426352
TIME (h)               2.991036
dtype: float64

In [19]:
data4tpyes=numeric_data.head(4).mean()

In [21]:
print(data4tpyes)

YEAR                 2012.500
(kW)                   71.250
CITY (kWh/100 km)      18.025
HWY (kWh/100 km)       21.725
COMB (kWh/100 km)      19.625
CITY (Le/100 km)        2.025
HWY (Le/100 km)         2.450
COMB (Le/100 km)        2.200
(g/km)                  0.000
RATING                    NaN
(km)                  109.750
TIME (h)                6.250
dtype: float64

In [22]:
data['TYPE'].value_counts()

TYPE
B    53
Name: count, dtype: int64

In [24]:
data['TIME (h)'].mean()

np.float64(8.471698113207546)