In [11]:
import pandas as pd
data=pd.read_csv('data_clean.csv')

In [12]:
data.head()

   Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4     67     5    1  2010    67       S
1           2   36.0    118.0   8.0     72     5    2  2010    72       C
2           3   12.0    149.0  12.6     74     5    3  2010    74      PS
3           4   18.0    313.0  11.5     62     5    4  2010    62       S
4           5    NaN      NaN  14.3     56     5    5  2010    56       S

In [13]:
data=data.drop('Unnamed: 0',axis=1)

In [14]:
data=data.drop('Temp C',axis=1)

In [15]:
data.head()

   Ozone  Solar.R  Wind Month  Day  Year  Temp Weather
0   41.0    190.0   7.4     5    1  2010    67       S
1   36.0    118.0   8.0     5    2  2010    72       C
2   12.0    149.0  12.6     5    3  2010    74      PS
3   18.0    313.0  11.5     5    4  2010    62       S
4    NaN      NaN  14.3     5    5  2010    56       S

In [16]:
data=data.rename({'Solar.R':'Solar'},axis=1)
data.head()

   Ozone  Solar  Wind Month  Day  Year  Temp Weather
0   41.0  190.0   7.4     5    1  2010    67       S
1   36.0  118.0   8.0     5    2  2010    72       C
2   12.0  149.0  12.6     5    3  2010    74      PS
3   18.0  313.0  11.5     5    4  2010    62       S
4    NaN    NaN  14.3     5    5  2010    56       S

In [18]:
data.shape

(158, 8)

In [19]:
data.columns.tolist()

['Ozone', 'Solar', 'Wind', 'Month', 'Day', 'Year', 'Temp', 'Weather']

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Ozone    120 non-null    float64
 1   Solar    151 non-null    float64
 2   Wind     158 non-null    float64
 3   Month    158 non-null    object
 4   Day      158 non-null    int64
 5   Year     158 non-null    int64
 6   Temp     158 non-null    int64
 7   Weather  155 non-null    object
dtypes: float64(3), int64(3), object(2)
memory usage: 10.0+ KB

In [26]:
data[data.duplicated()].shape

(1, 8)

In [27]:
print(data[data.duplicated()])

     Ozone  Solar  Wind Month  Day  Year  Temp Weather
156   14.0  191.0  14.3     9   28  2010    75       S

In [29]:
data=data.drop_duplicates()