In [11]:
import pandas as pd
data=pd.read_csv('data_clean.csv')

In [12]:
data.head()

   Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4     67     5    1  2010    67       S
1           2   36.0    118.0   8.0     72     5    2  2010    72       C
2           3   12.0    149.0  12.6     74     5    3  2010    74      PS
3           4   18.0    313.0  11.5     62     5    4  2010    62       S
4           5    NaN      NaN  14.3     56     5    5  2010    56       S

In [13]:
data=data.drop('Unnamed: 0',axis=1)

In [14]:
data=data.drop('Temp C',axis=1)

In [15]:
data.head()

   Ozone  Solar.R  Wind Month  Day  Year  Temp Weather
0   41.0    190.0   7.4     5    1  2010    67       S
1   36.0    118.0   8.0     5    2  2010    72       C
2   12.0    149.0  12.6     5    3  2010    74      PS
3   18.0    313.0  11.5     5    4  2010    62       S
4    NaN      NaN  14.3     5    5  2010    56       S

In [16]:
data=data.rename({'Solar.R':'Solar'},axis=1)
data.head()

   Ozone  Solar  Wind Month  Day  Year  Temp Weather
0   41.0  190.0   7.4     5    1  2010    67       S
1   36.0  118.0   8.0     5    2  2010    72       C
2   12.0  149.0  12.6     5    3  2010    74      PS
3   18.0  313.0  11.5     5    4  2010    62       S
4    NaN    NaN  14.3     5    5  2010    56       S

In [18]:
data.shape

(158, 8)

In [19]:
data.columns.tolist()

['Ozone', 'Solar', 'Wind', 'Month', 'Day', 'Year', 'Temp', 'Weather']

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Ozone    120 non-null    float64
 1   Solar    151 non-null    float64
 2   Wind     158 non-null    float64
 3   Month    158 non-null    object
 4   Day      158 non-null    int64
 5   Year     158 non-null    int64
 6   Temp     158 non-null    int64
 7   Weather  155 non-null    object
dtypes: float64(3), int64(3), object(2)
memory usage: 10.0+ KB

In [26]:
data[data.duplicated()].shape

(1, 8)

In [27]:
print(data[data.duplicated()])

     Ozone  Solar  Wind Month  Day  Year  Temp Weather
156   14.0  191.0  14.3     9   28  2010    75       S

In [29]:
data=data.drop_duplicates()

In [38]:
#changing of categories to numeric or vice versa
data[data['Month'].isna()]

Empty DataFrame
Columns: [Ozone, Solar, Wind, Month, Day, Year, Temp, Weather]
Index: []

In [39]:
data['Month'] = data['Month'].replace({'January': 1,'February': 2,'March': 3,'April': 4,'May': 5,'June': 6,'July': 7,'August': 8,'September': 9,'October': 10,'November': 11,
                                       'December': 12})

In [40]:
data[pd.to_numeric(data['Month'], errors='coerce').isna()]

Empty DataFrame
Columns: [Ozone, Solar, Wind, Month, Day, Year, Temp, Weather]
Index: []

In [41]:
data[data['Weather'].isna()]

    Ozone  Solar  Wind Month  Day  Year  Temp Weather
87   52.0   82.0  12.0     7   27  2010    86     NaN
93    9.0   24.0  13.8     8    2  2010    81     NaN
95   78.0    NaN   6.9     8    4  2010    86     NaN

In [44]:
data['Weather']=data['Weather'].astype('category')

In [45]:
data[data['Weather'].isna()]

    Ozone  Solar  Wind Month  Day  Year  Temp Weather
87   52.0   82.0  12.0     7   27  2010    86     NaN
93    9.0   24.0  13.8     8    2  2010    81     NaN
95   78.0    NaN   6.9     8    4  2010    86     NaN

In [46]:
data[data['Temp'].isna()]

Empty DataFrame
Columns: [Ozone, Solar, Wind, Month, Day, Year, Temp, Weather]
Index: []

In [47]:
data.isnull().sum()

Ozone      38
Solar       7
Wind        0
Month       0
Day         0
Year        0
Temp        0
Weather     3
dtype: int64

In [48]:
data[data['Solar'].isna()]

    Ozone  Solar  Wind Month  Day  Year  Temp Weather
4     NaN    NaN  14.3     5    5  2010    56       S
5    28.0    NaN  14.9     5    6  2010    66       C
10    7.0    NaN   6.9     5   11  2010    74       C
26    NaN    NaN   8.0     5   27  2010    57      PS
95   78.0    NaN   6.9     8    4  2010    86     NaN
96   35.0    NaN   7.4     8    5  2010    85       S
97   66.0    NaN   4.6     8    6  2010    87       C

In [49]:
m=data['Ozone'].mean()
data['Ozone']=data['Ozone'].fillna(m)

In [50]:
data.isnull().sum()

Ozone      0
Solar      7
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [51]:
n=data['Solar'].mean()
data['Solar']=data['Solar'].fillna(n)

In [52]:
data.isnull().sum()

Ozone      0
Solar      0
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [58]:
o=data['Weather'].mode()[0]
data['Weather']=data['Weather'].fillna(o)

In [59]:
data.isnull().sum()

Ozone      0
Solar      0
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

# Outlier detection