In [37]:
import pandas as pd
data=pd.read_csv('data_clean.csv')

In [38]:
data.head()

   Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4     67     5    1  2010    67       S
1           2   36.0    118.0   8.0     72     5    2  2010    72       C
2           3   12.0    149.0  12.6     74     5    3  2010    74      PS
3           4   18.0    313.0  11.5     62     5    4  2010    62       S
4           5    NaN      NaN  14.3     56     5    5  2010    56       S

In [39]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  158 non-null    int64
 1   Ozone       120 non-null    float64
 2   Solar.R     151 non-null    float64
 3   Wind        158 non-null    float64
 4   Temp C      158 non-null    object
 5   Month       158 non-null    object
 6   Day         158 non-null    int64
 7   Year        158 non-null    int64
 8   Temp        158 non-null    int64
 9   Weather     155 non-null    object
dtypes: float64(3), int64(4), object(3)
memory usage: 12.5+ KB

In [40]:
data.describe()

,Unnamed: 0,Ozone,Solar.R,Wind,Day,Year,Temp
count,158.000000,120.000000,151.000000,158.000000,158.000000,158.0,158.000000
mean,79.500000,41.583333,185.403974,9.957595,16.006329,2010.0,77.727848
std,45.754781,32.620709,88.723103,3.511261,8.997166,0.0,9.377877
min,1.000000,1.000000,7.000000,1.700000,1.000000,2010.0,56.000000
25%,40.250000,18.000000,119.000000,7.400000,8.000000,2010.0,72.000000
50%,79.500000,30.500000,197.000000,9.700000,16.000000,2010.0,78.500000
75%,118.750000,61.500000,257.000000,11.875000,24.000000,2010.0,84.000000
max,158.000000,168.000000,334.000000,20.700000,31.000000,2010.0,97.000000

In [41]:
data=data.drop('Unnamed: 0',axis=1)

In [42]:
data=data.drop('Temp C',axis=1)

In [43]:
data.head(3)

   Ozone  Solar.R  Wind Month  Day  Year  Temp Weather
0   41.0    190.0   7.4     5    1  2010    67       S
1   36.0    118.0   8.0     5    2  2010    72       C
2   12.0    149.0  12.6     5    3  2010    74      PS

In [44]:
data=data.rename({'Solar.R':'Solar'},axis=1)

In [45]:
data.head()

   Ozone  Solar  Wind Month  Day  Year  Temp Weather
0   41.0  190.0   7.4     5    1  2010    67       S
1   36.0  118.0   8.0     5    2  2010    72       C
2   12.0  149.0  12.6     5    3  2010    74      PS
3   18.0  313.0  11.5     5    4  2010    62       S
4    NaN    NaN  14.3     5    5  2010    56       S

In [46]:
data[data.duplicated()].shape

(1, 8)

In [47]:
data[data.duplicated()]

     Ozone  Solar  Wind Month  Day  Year  Temp Weather
156   14.0  191.0  14.3     9   28  2010    75       S

In [48]:
data=data.drop_duplicates()# dropped the duplicated data from list

In [49]:
data['Month'].isnull().sum()

np.int64(0)

In [50]:
data['Month'] = data['Month'].replace({
    'January':1, 'February':2, 'March':3,
    'April':4, 'May':5, 'June':6,
    'July':7, 'August':8, 'September':9,
    'October':10, 'November':11, 'December':12
})

In [51]:
data['Month'].head(50)

0     5
1     5
2     5
3     5
4     5
5     5
6     5
7     5
8     5
9     5
10    5
11    5
12    5
13    5
14    5
15    5
16    5
17    5
18    5
19    5
20    5
21    5
22    5
23    5
24    5
25    5
26    5
27    5
28    5
29    5
30    5
31    6
32    6
33    6
34    6
35    6
36    6
37    6
38    6
39    6
40    6
41    6
42    6
43    6
44    6
45    6
46    6
47    6
48    6
49    6
Name: Month, dtype: object