In [3]:
import pandas as pd

In [5]:
data=pd.read_csv("data_clean.csv")

In [7]:
data.head()

   Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4     67     5    1  2010    67       S
1           2   36.0    118.0   8.0     72     5    2  2010    72       C
2           3   12.0    149.0  12.6     74     5    3  2010    74      PS
3           4   18.0    313.0  11.5     62     5    4  2010    62       S
4           5    NaN      NaN  14.3     56     5    5  2010    56       S

In [8]:
data.tail()

     Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
153         154   41.0    190.0   7.4     67     5    1  2010    67       C
154         155   30.0    193.0   6.9     70     9   26  2010    70      PS
155         156    NaN    145.0  13.2     77     9   27  2010    77       S
156         157   14.0    191.0  14.3     75     9   28  2010    75       S
157         158   18.0    131.0   8.0     76     9   29  2010    76       C

In [9]:
data.describe()

,Unnamed: 0,Ozone,Solar.R,Wind,Day,Year,Temp
count,158.000000,120.000000,151.000000,158.000000,158.000000,158.0,158.000000
mean,79.500000,41.583333,185.403974,9.957595,16.006329,2010.0,77.727848
std,45.754781,32.620709,88.723103,3.511261,8.997166,0.0,9.377877
min,1.000000,1.000000,7.000000,1.700000,1.000000,2010.0,56.000000
25%,40.250000,18.000000,119.000000,7.400000,8.000000,2010.0,72.000000
50%,79.500000,30.500000,197.000000,9.700000,16.000000,2010.0,78.500000
75%,118.750000,61.500000,257.000000,11.875000,24.000000,2010.0,84.000000
max,158.000000,168.000000,334.000000,20.700000,31.000000,2010.0,97.000000

In [10]:
data.shape

(158, 10)

In [11]:
data.info

<bound method DataFrame.info of      Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0             1   41.0    190.0   7.4     67     5    1  2010    67       S
1             2   36.0    118.0   8.0     72     5    2  2010    72       C
2             3   12.0    149.0  12.6     74     5    3  2010    74      PS
3             4   18.0    313.0  11.5     62     5    4  2010    62       S
4             5    NaN      NaN  14.3     56     5    5  2010    56       S
..          ...    ...      ...   ...    ...   ...  ...   ...   ...     ...
153         154   41.0    190.0   7.4     67     5    1  2010    67       C
154         155   30.0    193.0   6.9     70     9   26  2010    70      PS
155         156    NaN    145.0  13.2     77     9   27  2010    77       S
156         157   14.0    191.0  14.3     75     9   28  2010    75       S
157         158   18.0    131.0   8.0     76     9   29  2010    76       C

[158 rows x 10 columns]>

In [12]:
data_bkp=data

In [14]:
data.dtypes

Unnamed: 0      int64
Ozone         float64
Solar.R       float64
Wind          float64
Temp C         object
Month          object
Day             int64
Year            int64
Temp            int64
Weather        object
dtype: object

In [16]:
data=data.drop('Unnamed: 0',axis=1)

In [17]:
data.head()

   Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0   41.0    190.0   7.4     67     5    1  2010    67       S
1   36.0    118.0   8.0     72     5    2  2010    72       C
2   12.0    149.0  12.6     74     5    3  2010    74      PS
3   18.0    313.0  11.5     62     5    4  2010    62       S
4    NaN      NaN  14.3     56     5    5  2010    56       S

In [18]:
data=data.drop('Temp C',axis=1)

In [19]:
data.head()

   Ozone  Solar.R  Wind Month  Day  Year  Temp Weather
0   41.0    190.0   7.4     5    1  2010    67       S
1   36.0    118.0   8.0     5    2  2010    72       C
2   12.0    149.0  12.6     5    3  2010    74      PS
3   18.0    313.0  11.5     5    4  2010    62       S
4    NaN      NaN  14.3     5    5  2010    56       S

In [20]:
data.shape

(158, 8)

# Practise2 LC 10

In [4]:
df_sal=pd.read_csv('salaries.csv')

In [5]:
df_sal.head()

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [6]:
df_sal.shape

(78, 6)

In [7]:
df_sal.dtypes

rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object

In [8]:
df_sal['salary'].dtypes

dtype('int64')

In [9]:
df_sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rank        78 non-null     object
 1   discipline  78 non-null     object
 2   phd         78 non-null     int64
 3   service     78 non-null     int64
 4   sex         78 non-null     object
 5   salary      78 non-null     int64
dtypes: int64(3), object(3)
memory usage: 3.8+ KB

In [10]:
df_sal[['phd','service']].std()

phd        12.498425
service    12.139768
dtype: float64

In [11]:
df_sal.head()

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [12]:
df_sal[['phd','service','salary']].std()

phd           12.498425
service       12.139768
salary     28293.661022
dtype: float64

In [13]:
df_sal['discipline'].value_counts()

discipline
B    42
A    36
Name: count, dtype: int64

In [14]:
df_sal.groupby(['discipline']).mean(numeric_only=True)

                  phd    service         salary
discipline
A           21.527778  15.722222   98331.111111
B           18.142857  14.476190  116331.785714

In [15]:
df_sal.groupby(['sex']).std(numeric_only=True)

              phd    service        salary
sex
Female   9.784176   8.813252  25952.127317
Male    14.138032  13.999711  29110.516397

In [17]:
df_sal.groupby(['sex'])[['salary','phd']].mean(numeric_only=True)

               salary        phd
sex
Female  101002.410256  16.512821
Male    115045.153846  22.897436

### Create data Frame

In [18]:
data1={'RollNo':[1,2,3],
    'Subject':['A','B','C']}

In [19]:
df1=pd.DataFrame(data1)

In [20]:
df1

   RollNo Subject
0       1       A
1       2       B
2       3       C

In [21]:
data2={'RollNo':[4,5,6],
      'Subject':['D','E','F']}

In [22]:
df2=pd.DataFrame(data2)

In [23]:
df2

   RollNo Subject
0       4       D
1       5       E
2       6       F

In [24]:
result_df=pd.concat([df1,df2],axis=0,ignore_index=True)
print(result_df)

   RollNo Subject
0       1       A
1       2       B
2       3       C
3       4       D
4       5       E
5       6       F

In [27]:
df3=pd.DataFrame({'ID':[1,2,3],'Name':['Alice','Bob','Charlie']})
df4=pd.DataFrame({'ID':[2,3,4],'Age':[25,30,35]})

In [29]:
merge_inner=pd.merge(df3,df4,on='ID',how='inner')

In [30]:
print('\n step 2:Inner Join(Default')
print(df3)

 step 2:Inner Join(Default
   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie

In [32]:
merge_outer=pd.merge(df3,df4,on='ID',how='outer')
print("\n Step 3:Outer Join")
print(merge_outer)

 Step 3:Outer Join
   ID     Name   Age
0   1    Alice   NaN
1   2      Bob  25.0
2   3  Charlie  30.0
3   4      NaN  35.0

In [34]:
merge_left=pd.merge(df3,df4,on='ID',how='left')
print("\n step 4: Left Join")
print(merge_left)

 step 4: Left Join
   ID     Name   Age
0   1    Alice   NaN
1   2      Bob  25.0
2   3  Charlie  30.0

In [35]:
merge_right=pd.merge(df3,df4,on='ID',how='right')
print("\n step 5:Right Join")
print(merge_right)

 step 5:Right Join
   ID     Name  Age
0   2      Bob   25
1   3  Charlie   30
2   4      NaN   35

## Filter

In [53]:
df_sal1=pd.read_csv('salaries.csv')

In [54]:
df_sal1

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

In [55]:
df_sal1.info

<bound method DataFrame.info of          rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]>

In [56]:
df_sal1.shape

(78, 6)

In [57]:
df_sal1.filter(items=['rank','salary'])

         rank  salary
0        Prof  186960
1        Prof   93000
2        Prof  110515
3        Prof  131205
4        Prof  104800
..        ...     ...
73       Prof  105450
74  AssocProf  104542
75       Prof  124312
76       Prof  109954
77       Prof  109646

[78 rows x 2 columns]

In [58]:
df_sal1[['rank','salary','sex']]

         rank  salary     sex
0        Prof  186960    Male
1        Prof   93000    Male
2        Prof  110515    Male
3        Prof  131205    Male
4        Prof  104800    Male
..        ...     ...     ...
73       Prof  105450  Female
74  AssocProf  104542  Female
75       Prof  124312  Female
76       Prof  109954  Female
77       Prof  109646  Female

[78 rows x 3 columns]

In [59]:
df_sal1[df_sal1['sex']=='Male']

         rank discipline  phd  service   sex  salary
0        Prof          B   56       49  Male  186960
1        Prof          A   12        6  Male   93000
2        Prof          A   23       20  Male  110515
3        Prof          A   40       31  Male  131205
4        Prof          B   20       18  Male  104800
5        Prof          A   20       20  Male  122400
6   AssocProf          A   20       17  Male   81285
7        Prof          A   18       18  Male  126300
8        Prof          A   29       19  Male   94350
9        Prof          A   51       51  Male   57800
10       Prof          B   39       33  Male  128250
11       Prof          B   23       23  Male  134778
12   AsstProf          B    1        0  Male   88000
13       Prof          B   35       33  Male  162200
14       Prof          B   25       19  Male  153750
15       Prof          B   17        3  Male  150480
16   AsstProf          B    8        3  Male   75044
17   AsstProf          B    4        0  Male   92000
18       Prof          A   19        7  Male  107300
19       Prof          A   29       27  Male  150500
20   AsstProf          B    4        4  Male   92000
21       Prof          A   33       30  Male  103106
22   AsstProf          A    4        2  Male   73000
23   AsstProf          A    2        0  Male   85000
24       Prof          A   30       23  Male   91100
25       Prof          B   35       31  Male   99418
26       Prof          A   38       19  Male  148750
27       Prof          A   45       43  Male  155865
28   AsstProf          B    7        2  Male   91300
29       Prof          B   21       20  Male  123683
30  AssocProf          B    9        7  Male  107008
31       Prof          B   22       21  Male  155750
32       Prof          A   27       19  Male  103275
33       Prof          B   18       18  Male  120000
34  AssocProf          B   12        8  Male  119800
35       Prof          B   28       23  Male  126933
36       Prof          B   45       45  Male  146856
37       Prof          A   20        8  Male  102000
38   AsstProf          B    4        3  Male   91000

In [60]:
df_sal1[df_sal1['salary']>120000]

    rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
3   Prof          A   40       31    Male  131205
5   Prof          A   20       20    Male  122400
7   Prof          A   18       18    Male  126300
10  Prof          B   39       33    Male  128250
11  Prof          B   23       23    Male  134778
13  Prof          B   35       33    Male  162200
14  Prof          B   25       19    Male  153750
15  Prof          B   17        3    Male  150480
19  Prof          A   29       27    Male  150500
26  Prof          A   38       19    Male  148750
27  Prof          A   45       43    Male  155865
29  Prof          B   21       20    Male  123683
31  Prof          B   22       21    Male  155750
35  Prof          B   28       23    Male  126933
36  Prof          B   45       45    Male  146856
39  Prof          B   18       18  Female  129000
40  Prof          A   39       36  Female  137000
44  Prof          B   23       19  Female  151768
45  Prof          B   25       25  Female  140096
49  Prof          B   17       18  Female  122960
51  Prof          B   20       14  Female  127512
58  Prof          B   36       26  Female  144651
72  Prof          B   24       15  Female  161101
75  Prof          B   17       17  Female  124312

In [75]:
df_sal1[df_sal1['sex'] == 'Female'][['rank','discipline','phd','service','salary','sex']]

         rank discipline  phd  service  salary     sex
39       Prof          B   18       18  129000  Female
40       Prof          A   39       36  137000  Female
41  AssocProf          A   13        8   74830  Female
42   AsstProf          B    4        2   80225  Female
43   AsstProf          B    5        0   77000  Female
44       Prof          B   23       19  151768  Female
45       Prof          B   25       25  140096  Female
46   AsstProf          B   11        3   74692  Female
47  AssocProf          B   11       11  103613  Female
48       Prof          B   17       17  111512  Female
49       Prof          B   17       18  122960  Female
50   AsstProf          B   10        5   97032  Female
51       Prof          B   20       14  127512  Female
52       Prof          A   12        0  105000  Female
53   AsstProf          A    5        3   73500  Female
54  AssocProf          A   25       22   62884  Female
55   AsstProf          A    2        0   72500  Female
56  AssocProf          A   10        8   77500  Female
57   AsstProf          A    3        1   72500  Female
58       Prof          B   36       26  144651  Female
59  AssocProf          B   12       10  103994  Female
60   AsstProf          B    3        3   92000  Female
61  AssocProf          B   13       10  103750  Female
62  AssocProf          B   14        7  109650  Female
63       Prof          A   29       27   91000  Female
64  AssocProf          A   26       24   73300  Female
65       Prof          A   36       19  117555  Female
66   AsstProf          A    7        6   63100  Female
67       Prof          A   17       11   90450  Female
68   AsstProf          A    4        2   77500  Female
69       Prof          A   28        7  116450  Female
70   AsstProf          A    8        3   78500  Female
71  AssocProf          B   12        9   71065  Female
72       Prof          B   24       15  161101  Female
73       Prof          B   18       10  105450  Female
74  AssocProf          B   19        6  104542  Female
75       Prof          B   17       17  124312  Female
76       Prof          A   28       14  109954  Female
77       Prof          A   23       15  109646  Female

In [77]:
df_sal1[(df_sal1['salary']>120000)&(df_sal['discipline']=='B')]

    rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
10  Prof          B   39       33    Male  128250
11  Prof          B   23       23    Male  134778
13  Prof          B   35       33    Male  162200
14  Prof          B   25       19    Male  153750
15  Prof          B   17        3    Male  150480
29  Prof          B   21       20    Male  123683
31  Prof          B   22       21    Male  155750
35  Prof          B   28       23    Male  126933
36  Prof          B   45       45    Male  146856
39  Prof          B   18       18  Female  129000
44  Prof          B   23       19  Female  151768
45  Prof          B   25       25  Female  140096
49  Prof          B   17       18  Female  122960
51  Prof          B   20       14  Female  127512
58  Prof          B   36       26  Female  144651
72  Prof          B   24       15  Female  161101
75  Prof          B   17       17  Female  124312

In [78]:
#rank = prof
#sex=female
df_sal1[(df_sal1['rank']=='Prof')&(df_sal1['sex']=='Female')]

    rank discipline  phd  service     sex  salary
39  Prof          B   18       18  Female  129000
40  Prof          A   39       36  Female  137000
44  Prof          B   23       19  Female  151768
45  Prof          B   25       25  Female  140096
48  Prof          B   17       17  Female  111512
49  Prof          B   17       18  Female  122960
51  Prof          B   20       14  Female  127512
52  Prof          A   12        0  Female  105000
58  Prof          B   36       26  Female  144651
63  Prof          A   29       27  Female   91000
65  Prof          A   36       19  Female  117555
67  Prof          A   17       11  Female   90450
69  Prof          A   28        7  Female  116450
72  Prof          B   24       15  Female  161101
73  Prof          B   18       10  Female  105450
75  Prof          B   17       17  Female  124312
76  Prof          A   28       14  Female  109954
77  Prof          A   23       15  Female  109646

## Creating a bonus coloumn using salary

In [80]:
df_sal1['bonus']=df_sal['salary']*0.1

In [81]:
df_sal1

         rank discipline  phd  service     sex  salary    bonus
0        Prof          B   56       49    Male  186960  18696.0
1        Prof          A   12        6    Male   93000   9300.0
2        Prof          A   23       20    Male  110515  11051.5
3        Prof          A   40       31    Male  131205  13120.5
4        Prof          B   20       18    Male  104800  10480.0
..        ...        ...  ...      ...     ...     ...      ...
73       Prof          B   18       10  Female  105450  10545.0
74  AssocProf          B   19        6  Female  104542  10454.2
75       Prof          B   17       17  Female  124312  12431.2
76       Prof          A   28       14  Female  109954  10995.4
77       Prof          A   23       15  Female  109646  10964.6

[78 rows x 7 columns]

## Creating a new phd

In [82]:
df_sal1['new_phd']=df_sal1['phd']+10

In [83]:
df_sal1

         rank discipline  phd  service     sex  salary    bonus  new_phd
0        Prof          B   56       49    Male  186960  18696.0       66
1        Prof          A   12        6    Male   93000   9300.0       22
2        Prof          A   23       20    Male  110515  11051.5       33
3        Prof          A   40       31    Male  131205  13120.5       50
4        Prof          B   20       18    Male  104800  10480.0       30
..        ...        ...  ...      ...     ...     ...      ...      ...
73       Prof          B   18       10  Female  105450  10545.0       28
74  AssocProf          B   19        6  Female  104542  10454.2       29
75       Prof          B   17       17  Female  124312  12431.2       27
76       Prof          A   28       14  Female  109954  10995.4       38
77       Prof          A   23       15  Female  109646  10964.6       33

[78 rows x 8 columns]

## Create a ew total which adds salary and bonus

In [85]:
df_sal1['total']=df_sal1['bonus']+df_sal1['salary']

In [86]:
df_sal1

,rank,discipline,phd,service,sex,salary,bonus,new_phd,total
0,Prof,B,56,49,Male,186960,18696.0,66,205656.0
1,Prof,A,12,6,Male,93000,9300.0,22,102300.0
2,Prof,A,23,20,Male,110515,11051.5,33,121566.5
3,Prof,A,40,31,Male,131205,13120.5,50,144325.5
4,Prof,B,20,18,Male,104800,10480.0,30,115280.0
...,...,...,...,...,...,...,...,...,...
73,Prof,B,18,10,Female,105450,10545.0,28,115995.0
74,AssocProf,B,19,6,Female,104542,10454.2,29,114996.2
75,Prof,B,17,17,Female,124312,12431.2,27,136743.2
76,Prof,A,28,14,Female,109954,10995.4,38,120949.4
77,Prof,A,23,15,Female,109646,10964.6,33,120610.6

In [87]:
df_sal1.shape

(78, 9)