In [1]:
import pandas as pd # pd is basically alias of pandas

In [3]:
df_sal=pd.read_csv('salaries.csv')

In [5]:
df_sal.head()

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [7]:
df_sal.head(20)

         rank discipline  phd  service   sex  salary
0        Prof          B   56       49  Male  186960
1        Prof          A   12        6  Male   93000
2        Prof          A   23       20  Male  110515
3        Prof          A   40       31  Male  131205
4        Prof          B   20       18  Male  104800
5        Prof          A   20       20  Male  122400
6   AssocProf          A   20       17  Male   81285
7        Prof          A   18       18  Male  126300
8        Prof          A   29       19  Male   94350
9        Prof          A   51       51  Male   57800
10       Prof          B   39       33  Male  128250
11       Prof          B   23       23  Male  134778
12   AsstProf          B    1        0  Male   88000
13       Prof          B   35       33  Male  162200
14       Prof          B   25       19  Male  153750
15       Prof          B   17        3  Male  150480
16   AsstProf          B    8        3  Male   75044
17   AsstProf          B    4        0  Male   92000
18       Prof          A   19        7  Male  107300
19       Prof          A   29       27  Male  150500

In [9]:
df_sal.shape

(78, 6)

In [10]:
df_sal['sex']

0       Male
1       Male
2       Male
3       Male
4       Male
       ...
73    Female
74    Female
75    Female
76    Female
77    Female
Name: sex, Length: 78, dtype: object

In [11]:
df_sal['sex'].head(20)

0     Male
1     Male
2     Male
3     Male
4     Male
5     Male
6     Male
7     Male
8     Male
9     Male
10    Male
11    Male
12    Male
13    Male
14    Male
15    Male
16    Male
17    Male
18    Male
19    Male
Name: sex, dtype: object

In [18]:
df_sal['salary'].dtypes

dtype('int64')

In [20]:
df_sal.dtypes #data types of all columns(features)

rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object

In [22]:
 df_sal['salary'].std()

np.float64(28293.66102226417)

In [23]:
df_sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rank        78 non-null     object
 1   discipline  78 non-null     object
 2   phd         78 non-null     int64
 3   service     78 non-null     int64
 4   sex         78 non-null     object
 5   salary      78 non-null     int64
dtypes: int64(3), object(3)
memory usage: 3.8+ KB

In [25]:
df_sal[['phd','service']].std()

phd        12.498425
service    12.139768
dtype: float64

In [32]:
df_sal[['phd','service','salary']].std()

phd           12.498425
service       12.139768
salary     28293.661022
dtype: float64

In [33]:
df_sal.head()

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [34]:
df_sal['rank'].value_counts()

rank
Prof         46
AsstProf     19
AssocProf    13
Name: count, dtype: int64

In [35]:
df_sal['discipline'].value_counts()

discipline
B    42
A    36
Name: count, dtype: int64

In [41]:
df_sal.groupby('discipline').mean(numeric_only=True)

                  phd    service         salary
discipline
A           21.527778  15.722222   98331.111111
B           18.142857  14.476190  116331.785714

In [47]:
df_sal.groupby(['sex']).mean(numeric_only=True)

              phd    service         salary
sex
Female  16.512821  11.564103  101002.410256
Male    22.897436  18.538462  115045.153846

In [49]:
df_sal.groupby(['sex'])[['salary','phd']].mean(numeric_only=True)

               salary        phd
sex
Female  101002.410256  16.512821
Male    115045.153846  22.897436

In [50]:
df_sal.groupby(['discipline'])[['salary']].mean(numeric_only=True)

                   salary
discipline
A            98331.111111
B           116331.785714