In [2]:
import pandas as pd
sal_data=pd.read_csv('sal_data.csv')
bonus_data=pd.read_csv('bonus_data.csv')

In [4]:
sal_data.head()

  Employee_ID First_Name Last_Name  Basic_Salary
0      E-1001     Mahesh     Joshi         16860
1      E-1002     Rajesh     Kolte         14960
2      E-1004      Priya      Jain         12670
3      E-1005      Sneha     Joshi         15660
4      E-1007        Ram    Kanade         15850

In [5]:
bonus_data.head()

  Employee_ID  Bonus
0      E-1001  16070
1      E-1003  15200
2      E-1004  13490
3      E-1006  14200
4      E-1008  15880

In [8]:
left_join=pd.merge(sal_data,bonus_data,how='left')

In [9]:
left_join

  Employee_ID First_Name Last_Name  Basic_Salary    Bonus
0      E-1001     Mahesh     Joshi         16860  16070.0
1      E-1002     Rajesh     Kolte         14960      NaN
2      E-1004      Priya      Jain         12670  13490.0
3      E-1005      Sneha     Joshi         15660      NaN
4      E-1007        Ram    Kanade         15850      NaN
5      E-1008      Nishi    Honrao         15950  15880.0
6      E-1009     Hameed     Singh         15120      NaN

In [10]:
right_join=pd.merge(sal_data,bonus_data,how='right')

In [11]:
right_join

  Employee_ID First_Name Last_Name  Basic_Salary  Bonus
0      E-1001     Mahesh     Joshi       16860.0  16070
1      E-1003        NaN       NaN           NaN  15200
2      E-1004      Priya      Jain       12670.0  13490
3      E-1006        NaN       NaN           NaN  14200
4      E-1008      Nishi    Honrao       15950.0  15880
5      E-1010        NaN       NaN           NaN  15120

In [12]:
inner_join=pd.merge(sal_data,bonus_data,how='inner')

In [13]:
inner_join

  Employee_ID First_Name Last_Name  Basic_Salary  Bonus
0      E-1001     Mahesh     Joshi         16860  16070
1      E-1004      Priya      Jain         12670  13490
2      E-1008      Nishi    Honrao         15950  15880

## Appending

In [17]:
import pandas as pd
salary1=pd.read_csv('basic_salary_1.csv')

In [18]:
salary2=pd.read_csv('basic_salary_2.csv')

In [19]:
appendsalary=pd.concat([salary1,salary2])

In [20]:
appendsalary

  First_Name Last_Name Grade Location     ba     ms
0       Alan     Brown   GR1    DELHI  17990  16070
1     Agatha  Williams   GR2   MUMBAI  12390   6630
2     Rajesh     Kolte   GR1   MUMBAI  19250  14960
3      Ameet    Mishra   GR2    DELHI  14780   9300
4       Neha       Rao   GR1   MUMBAI  19235  15200
0      Sagar    Chavan   GR2   MUMBAI  13390   6700
1      Aaron     Jones   GR1   MUMBAI  23280  13490
2       John     Patil   GR2   MUMBAI  13500  10760
3      Sneha     Joshi   GR1    DELHI  20660      0
4     Gaurav     Singh   GR2    DELHI  13760  13220
5      Adela    Thomas   GR2    DELHI  13660   6840
6       Anup      Save   GR2   MUMBAI  11960   7880

In [22]:
import pandas as pd
salary_data=pd.read_csv('basic_salary.csv')

In [23]:
salary_data.head()

  First_Name Last_Name Grade Location     ba     ms
0       Alan     Brown   GR1    DELHI  17990  16070
1     Agatha  Williams   GR2   MUMBAI  12390   6630
2     Rajesh     Kolte   GR1   MUMBAI  19250  14960
3      Ameet    Mishra   GR2    DELHI  14780   9300
4       Neha       Rao   GR1   MUMBAI  19235  15200

## aggregation

In [29]:
A=salary_data.groupby('Location')['ba'].sum()

In [30]:
A

Location
DELHI     32770
MUMBAI    50875
Name: ba, dtype: int64

In [32]:
B = salary_data.groupby('Location')[['ba','ms']].sum()

In [33]:
B

             ba     ms
Location
DELHI     32770  25370
MUMBAI    50875  36790

In [34]:
C=salary_data.groupby(['Location','Grade'])[['ba','ms']].sum()

In [35]:
C

                   ba     ms
Location Grade
DELHI    GR1    17990  16070
         GR2    14780   9300
MUMBAI   GR1    38485  30160
         GR2    12390   6630