In [2]:
import pandas as pd
sal_data=pd.read_csv('sal_data.csv')
bonus_data=pd.read_csv('bonus_data.csv')

In [4]:
sal_data.head()

  Employee_ID First_Name Last_Name  Basic_Salary
0      E-1001     Mahesh     Joshi         16860
1      E-1002     Rajesh     Kolte         14960
2      E-1004      Priya      Jain         12670
3      E-1005      Sneha     Joshi         15660
4      E-1007        Ram    Kanade         15850

In [5]:
bonus_data.head()

  Employee_ID  Bonus
0      E-1001  16070
1      E-1003  15200
2      E-1004  13490
3      E-1006  14200
4      E-1008  15880

In [8]:
left_join=pd.merge(sal_data,bonus_data,how='left')

In [9]:
left_join

  Employee_ID First_Name Last_Name  Basic_Salary    Bonus
0      E-1001     Mahesh     Joshi         16860  16070.0
1      E-1002     Rajesh     Kolte         14960      NaN
2      E-1004      Priya      Jain         12670  13490.0
3      E-1005      Sneha     Joshi         15660      NaN
4      E-1007        Ram    Kanade         15850      NaN
5      E-1008      Nishi    Honrao         15950  15880.0
6      E-1009     Hameed     Singh         15120      NaN

In [10]:
right_join=pd.merge(sal_data,bonus_data,how='right')

In [11]:
right_join

  Employee_ID First_Name Last_Name  Basic_Salary  Bonus
0      E-1001     Mahesh     Joshi       16860.0  16070
1      E-1003        NaN       NaN           NaN  15200
2      E-1004      Priya      Jain       12670.0  13490
3      E-1006        NaN       NaN           NaN  14200
4      E-1008      Nishi    Honrao       15950.0  15880
5      E-1010        NaN       NaN           NaN  15120

In [12]:
inner_join=pd.merge(sal_data,bonus_data,how='inner')

In [13]:
inner_join

  Employee_ID First_Name Last_Name  Basic_Salary  Bonus
0      E-1001     Mahesh     Joshi         16860  16070
1      E-1004      Priya      Jain         12670  13490
2      E-1008      Nishi    Honrao         15950  15880

## Appending