In [1]:
import pandas as pd
data=pd.read_csv('data_clean.csv')

In [2]:
data.head(5)

   Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4     67     5    1  2010    67       S
1           2   36.0    118.0   8.0     72     5    2  2010    72       C
2           3   12.0    149.0  12.6     74     5    3  2010    74      PS
3           4   18.0    313.0  11.5     62     5    4  2010    62       S
4           5    NaN      NaN  14.3     56     5    5  2010    56       S

In [3]:
data_original=data

In [4]:
data=data.drop('Unnamed: 0',axis=1)

In [5]:
data.head(1)

   Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0   41.0    190.0   7.4     67     5    1  2010    67       S

In [6]:
data=data.drop('Temp C',axis=1)

In [7]:
data.head(1)

   Ozone  Solar.R  Wind Month  Day  Year  Temp Weather
0   41.0    190.0   7.4     5    1  2010    67       S

In [10]:
data=data.rename({'Solar.R':'Solar'},axis=1)

In [11]:
data.head(1)

   Ozone  Solar  Wind Month  Day  Year  Temp Weather
0   41.0  190.0   7.4     5    1  2010    67       S

In [12]:
data.isnull().sum()

Ozone      38
Solar       7
Wind        0
Month       0
Day         0
Year        0
Temp        0
Weather     3
dtype: int64

In [13]:
data['Temp']=pd.to_numeric(data['Temp'],errors='coerce')

In [14]:
data['Month']=pd.to_numeric(data['Month'],errors='coerce')

In [15]:
data['Month']=data['Month'].fillna(5)

In [16]:
data['Weather']=data['Weather'].astype('category')

In [17]:
data.isnull().sum()

Ozone      38
Solar       7
Wind        0
Month       0
Day         0
Year        0
Temp        0
Weather     3
dtype: int64

In [18]:
data.head(10)

   Ozone  Solar  Wind  Month  Day  Year  Temp Weather
0   41.0  190.0   7.4    5.0    1  2010    67       S
1   36.0  118.0   8.0    5.0    2  2010    72       C
2   12.0  149.0  12.6    5.0    3  2010    74      PS
3   18.0  313.0  11.5    5.0    4  2010    62       S
4    NaN    NaN  14.3    5.0    5  2010    56       S
5   28.0    NaN  14.9    5.0    6  2010    66       C
6   23.0  299.0   8.6    5.0    7  2010    65      PS
7   19.0   99.0  13.8    5.0    8  2010    59       C
8    8.0   19.0  20.1    5.0    9  2010    61      PS
9    NaN  194.0   8.6    5.0   10  2010    69       S

In [20]:
n=data['Ozone'].mean()
data['Ozone']=data['Ozone'].fillna(n)
data['Ozone'].isnull().sum()
data.head(7)

       Ozone  Solar  Wind  Month  Day  Year  Temp Weather
0  41.000000  190.0   7.4    5.0    1  2010    67       S
1  36.000000  118.0   8.0    5.0    2  2010    72       C
2  12.000000  149.0  12.6    5.0    3  2010    74      PS
3  18.000000  313.0  11.5    5.0    4  2010    62       S
4  41.583333    NaN  14.3    5.0    5  2010    56       S
5  28.000000    NaN  14.9    5.0    6  2010    66       C
6  23.000000  299.0   8.6    5.0    7  2010    65      PS

In [22]:
n=data['Solar'].mean()
data['Solar']=data['Solar'].fillna(n)
data.head(7)

       Ozone       Solar  Wind  Month  Day  Year  Temp Weather
0  41.000000  190.000000   7.4    5.0    1  2010    67       S
1  36.000000  118.000000   8.0    5.0    2  2010    72       C
2  12.000000  149.000000  12.6    5.0    3  2010    74      PS
3  18.000000  313.000000  11.5    5.0    4  2010    62       S
4  41.583333  185.403974  14.3    5.0    5  2010    56       S
5  28.000000  185.403974  14.9    5.0    6  2010    66       C
6  23.000000  299.000000   8.6    5.0    7  2010    65      PS

In [29]:
data1=pd.get_dummies(data,columns=['Weather'],dtype=int)

In [30]:
data1.head(5)

,Ozone,Solar,Wind,Month,Day,Year,Temp,Weather_C,Weather_PS,Weather_S
0,41.000000,190.000000,7.4,5.0,1,2010,67,0,0,1
1,36.000000,118.000000,8.0,5.0,2,2010,72,1,0,0
2,12.000000,149.000000,12.6,5.0,3,2010,74,0,1,0
3,18.000000,313.000000,11.5,5.0,4,2010,62,0,0,1
4,41.583333,185.403974,14.3,5.0,5,2010,56,0,0,1

# normalization

In [36]:
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler

In [37]:
array=data1

In [39]:
scaler=MinMaxScaler(feature_range=(0,1))
rescaledX=scaler.fit_transform(array)
set_printoptions(precision=2)
print(rescaledX[0:5,:])

[[0.24 0.56 0.3  0.   0.   0.   0.27 0.   0.   1.  ]
 [0.21 0.34 0.33 0.   0.03 0.   0.39 1.   0.   0.  ]
 [0.07 0.43 0.57 0.   0.07 0.   0.44 0.   1.   0.  ]
 [0.1  0.94 0.52 0.   0.1  0.   0.15 0.   0.   1.  ]
 [0.24 0.55 0.66 0.   0.13 0.   0.   0.   0.   1.  ]]

In [40]:
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler
array=data1
scaler=MinMaxScaler(feature_range=(0,1))
rescaledX=scaler.fit_transform(array)
set_printoptions(precision=2)
print(rescaledX)

[[0.24 0.56 0.3  ... 0.   0.   1.  ]
 [0.21 0.34 0.33 ... 1.   0.   0.  ]
 [0.07 0.43 0.57 ... 0.   1.   0.  ]
 ...
 [0.24 0.42 0.61 ... 0.   0.   1.  ]
 [0.08 0.56 0.66 ... 0.   0.   1.  ]
 [0.1  0.38 0.33 ... 1.   0.   0.  ]]

In [43]:
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler
array=data1
scaler=MinMaxScaler(feature_range=(0,1))
rescaled=scaler.fit_transform(array)
set_printoptions(precision=2)
print(rescaled)

[[0.24 0.56 0.3  ... 0.   0.   1.  ]
 [0.21 0.34 0.33 ... 1.   0.   0.  ]
 [0.07 0.43 0.57 ... 0.   1.   0.  ]
 ...
 [0.24 0.42 0.61 ... 0.   0.   1.  ]
 [0.08 0.56 0.66 ... 0.   0.   1.  ]
 [0.1  0.38 0.33 ... 1.   0.   0.  ]]

In [47]:
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler
array=data1
scaler=MinMaxScaler(feature_range=(0,1))
rescaled=scaler.fit_transform(array)
set_printoptions(precision=2)
print(rescaled)

[[0.24 0.56 0.3  ... 0.   0.   1.  ]
 [0.21 0.34 0.33 ... 1.   0.   0.  ]
 [0.07 0.43 0.57 ... 0.   1.   0.  ]
 ...
 [0.24 0.42 0.61 ... 0.   0.   1.  ]
 [0.08 0.56 0.66 ... 0.   0.   1.  ]
 [0.1  0.38 0.33 ... 1.   0.   0.  ]]

In [48]:
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler
array=data1
scaler=MinMaxScaler(feature_range=(0,1))
RescaledX=scaler.fit_transform(array)
set_printoptions(precision=2)
print(RescaledX)

[[0.24 0.56 0.3  ... 0.   0.   1.  ]
 [0.21 0.34 0.33 ... 1.   0.   0.  ]
 [0.07 0.43 0.57 ... 0.   1.   0.  ]
 ...
 [0.24 0.42 0.61 ... 0.   0.   1.  ]
 [0.08 0.56 0.66 ... 0.   0.   1.  ]
 [0.1  0.38 0.33 ... 1.   0.   0.  ]]

In [49]:
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler
array=data1
scaler=MinMaxScaler(feature_range=(0,1))
rescaledxx=scaler.fit_transform(array)
set_printoptions(precision=2)
print(rescaledxx)

[[0.24 0.56 0.3  ... 0.   0.   1.  ]
 [0.21 0.34 0.33 ... 1.   0.   0.  ]
 [0.07 0.43 0.57 ... 0.   1.   0.  ]
 ...
 [0.24 0.42 0.61 ... 0.   0.   1.  ]
 [0.08 0.56 0.66 ... 0.   0.   1.  ]
 [0.1  0.38 0.33 ... 1.   0.   0.  ]]

In [54]:
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler
a=data1
scalerr=MinMaxScaler(feature_range=(0,1))
xx=scalerr.fit_transform(a)
set_printoptions(precision=2)
print(xx)

[[0.24 0.56 0.3  ... 0.   0.   1.  ]
 [0.21 0.34 0.33 ... 1.   0.   0.  ]
 [0.07 0.43 0.57 ... 0.   1.   0.  ]
 ...
 [0.24 0.42 0.61 ... 0.   0.   1.  ]
 [0.08 0.56 0.66 ... 0.   0.   1.  ]
 [0.1  0.38 0.33 ... 1.   0.   0.  ]]