In [2]:
import pandas as pd
data=pd.read_csv('data_clean.csv')

In [3]:
data.head(5)

   Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4     67     5    1  2010    67       S
1           2   36.0    118.0   8.0     72     5    2  2010    72       C
2           3   12.0    149.0  12.6     74     5    3  2010    74      PS
3           4   18.0    313.0  11.5     62     5    4  2010    62       S
4           5    NaN      NaN  14.3     56     5    5  2010    56       S

In [5]:
data=data.drop('Unnamed: 0',axis=1)

In [6]:
data.head(2)

   Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0   41.0    190.0   7.4     67     5    1  2010    67       S
1   36.0    118.0   8.0     72     5    2  2010    72       C

In [7]:
data=data.drop('Temp C',axis=1)

In [8]:
data.head(2)

   Ozone  Solar.R  Wind Month  Day  Year  Temp Weather
0   41.0    190.0   7.4     5    1  2010    67       S
1   36.0    118.0   8.0     5    2  2010    72       C

In [9]:
data['Month'].isnull().sum()

np.int64(0)

In [11]:
data['Ozone'].isnull().sum()

np.int64(38)

In [12]:
data['Month']=pd.to_numeric(data['Month'],errors='coerce')

In [15]:
data['Month'].isnull().sum()

np.int64(0)

In [16]:
data['Month']=data['Month'].fillna(5)

In [17]:
data['Month'].isnull().sum()

np.int64(0)

In [18]:
data['Temp']=pd.to_numeric(data['Temp'],errors='coerce')

In [19]:
data['Temp'].isnull().sum()

np.int64(0)

In [20]:
data['Weather']=data['Weather'].astype('category')

In [22]:
data['Weather'].isnull().sum()

np.int64(3)

In [23]:
data.isnull().sum()

Ozone      38
Solar.R     7
Wind        0
Month       0
Day         0
Year        0
Temp        0
Weather     3
dtype: int64

In [ ]:
#Duplicated data